# Docker-compose file to built both the typedocs and sphinx for this repo locally (outputs to docs/build/html/)
# COMMMAND TO RUN FOR BUILDING: docker-compose -f docker-compose-docs.yaml up
version: "2.4"
services: 
  docs-build:
    build: # "context" and "dockerfile" fields have to be under "build"
      dockerfile: ./docs/Dockerfile
      context: .
    volumes:
    - ./:/src
    command:
      - /bin/bash
      - -c
      - |
        npm install
        npx typedoc ./src --out ./docs/sphinx/_static/typedocs
        cd ./docs/sphinx
        make html