version: "3.8"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/src
    image: node:lts-buster-slim
    networks:
      - dj-gui-react
    working_dir: /src/
    command: "npm start"

networks:
  dj-gui-react:
    external: 
      name: dj-gui-api